export type EditorChangeType =
    | 'adjust-depth'
    | 'apply-entity'
    | 'backspace-character'
    | 'change-block-data'
    | 'change-block-type'
    | 'change-inline-style'
    | 'move-block'
    | 'delete-character'
    | 'insert-characters'
    | 'insert-fragment'
    | 'redo'
    | 'remove-range'
    | 'spellcheck-change'
    | 'split-block'
    | 'undo';
